/**
 * Defines the graph editor model.
 * <p>
 * Classes are auto generated by Eclipse EMF, see <code>graph.ecore</code> and
 * <code>graph.genmodel</code>
 */
module com.ergotech.grapheditor.model {
  requires javafx.base;
  requires javafx.controls;
  requires java.desktop;

  exports com.ergotech.grapheditor.model;
  exports com.ergotech.grapheditor.model.command;
}